// This file is auto-generated by Lovable. Do not modify it.
// Supabase has been removed. OAuth is not available in local mode.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
const lovableAuth = createLovableAuth({});

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: { redirect_uri?: string }) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        ...opts,
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      // OAuth session setting removed — Supabase no longer used
      return result;
    },
  },
};
